require "WoC_classifier/extractor/AbstractExtractor.rb"
require "WoC_classifier/extractor/AdoptionExtractor.rb"
require "WoC_classifier/extractor/ChurnExtractor.rb"
require "WoC_classifier/extractor/CouplingExtractor.rb"
require "WoC_classifier/extractor/OverviewExtractor.rb"
require "WoC_classifier/extractor/SizeExtractor.rb"
